export default {
  members: [
    {
      id: 0,
      login: 'root',
      password: 'root',
      role: 'admin',
    },
    {
      id: 1,
      firstname: 'Felicia',
      lastname: 'Hess',
      hired_at: '2020-03-23',
      position: 'position',
      department: 'department',
      supervisor: '',
      subordinates: [],
      role: 'user',
      login: 'Hess',
      password: 'password',
    },
    {
      id: 2,
      firstname: 'Alston',
      lastname: 'Ramos',
      hired_at: '2014-12-25',
      position: 'position',
      department: 'department',
      supervisor: '',
      subordinates: [],
      role: 'user',
      login: 'Ramos',
      password: 'password',
    },
    {
      id: 3,
      firstname: 'April',
      lastname: 'Bradford',
      hired_at: '2014-10-26',
      position: 'position',
      department: 'department',
      supervisor: '',
      subordinates: [],
      role: 'user',
      login: 'Bradford',
      password: 'password',
    },
    {
      id: 4,
      firstname: 'Pitts',
      lastname: 'Bruce',
      hired_at: '2018-02-17',
      position: 'position',
      department: 'department',
      supervisor: '',
      subordinates: [],
      role: 'user',
      login: 'Bruce',
      password: 'password',
    },
    {
      id: 5,
      firstname: 'Nunez',
      lastname: 'Massey',
      hired_at: '2015-10-29',
      position: 'position',
      department: 'department',
      supervisor: '',
      subordinates: [],
      role: 'user',
      login: 'Massey',
      password: 'password',
    },
    {
      id: 6,
      firstname: 'Downs',
      lastname: 'Singleton',
      hired_at: '2019-06-13',
      position: 'position',
      department: 'department',
      supervisor: '',
      subordinates: [],
      role: 'user',
      login: 'Singleton',
      password: 'password',
    },
    {
      id: 7,
      firstname: 'Roxie',
      lastname: 'Kaufman',
      hired_at: '2016-11-17',
      position: 'position',
      department: 'department',
      supervisor: '',
      subordinates: [],
      role: 'user',
      login: 'Kaufman',
      password: 'password',
    },
    {
      id: 8,
      firstname: 'Lara',
      lastname: 'Hardin',
      hired_at: '2014-03-27',
      position: 'position',
      department: 'department',
      supervisor: '',
      subordinates: [],
      role: 'user',
      login: 'Hardin',
      password: 'password',
    },
    {
      id: 9,
      firstname: 'Dixon',
      lastname: 'Mcconnell',
      hired_at: '2020-01-17',
      position: 'position',
      department: 'department',
      supervisor: '',
      subordinates: [],
      role: 'user',
      login: 'Mcconnell',
      password: 'password',
    },
    {
      id: 10,
      firstname: 'Karla',
      lastname: 'Thornton',
      hired_at: '2018-08-23',
      position: 'position',
      department: 'department',
      supervisor: '',
      subordinates: [],
      role: 'user',
      login: 'Thornton',
      password: 'password',
    },
    {
      id: 11,
      firstname: 'Mullen',
      lastname: 'Lamb',
      hired_at: '2020-06-18',
      position: 'position',
      department: 'department',
      supervisor: '',
      subordinates: [],
      role: 'user',
      login: 'Lamb',
      password: 'password',
    },
    {
      id: 12,
      firstname: 'Maryanne',
      lastname: 'Dodson',
      hired_at: '2020-02-18',
      position: 'position',
      department: 'department',
      supervisor: '',
      subordinates: [],
      role: 'user',
      login: 'Dodson',
      password: 'password',
    },
  ],
};
